### ISSUE TITLE
Request: UITextField border for bottom

### ISSUE THREAD

**Issue by laohanme** [PowerUpX/PowerUpSwift#2]
<img width="223" alt="image" src="https://user-images.githubusercontent.com/18119268/47977086-2fe3d280-e0f1-11e8-99da-9d35f766a99d.png">

**Comment by cefjoeii** [comment]
@laohanme Here ya go! [PowerUpUnderlineTextField](https://github.com/PowerUpX/PowerUpSwift/wiki/PowerUpUnderlineTextField
)

Sorry, I only had time to do it this weekend. Time to rest and sleep! 😅😴

**Comment by laohanme** [comment]
Bravo!! Thank you @cefjoeii you done it in professional way and have the error colour underline.
Time to take a rest, Happy coding

**Comment by cefjoeii** [comment]
Awesome! Thank you. 👍
